services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sveta_todo
    ports:
      - "5433:5432"
    volumes:
      - .docker/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sveta_todo"]
      interval: 5s
      timeout: 5s
      retries: 10
